/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HealthCareUI;

import HealthCare.Doctor;
import HealthCare.Encounter;
import HealthCare.Hospital;
import HealthCare.Patient;
import HealthCare.SystemAdmin;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pavan
 */
public class DoctorViewAppointment extends javax.swing.JPanel {
public Doctor doctor;

    /**
     * Creates new form DoctorViewAppointment
     */
    public DoctorViewAppointment(Doctor p) {
        initComponents();
        doctor=p;
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        patientCommunity = new javax.swing.JTextField();
        patientCity = new javax.swing.JTextField();
        patientGender = new javax.swing.JTextField();
        patientName = new javax.swing.JTextField();
        patientID = new javax.swing.JTextField();
        patientPass1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 1, 18)); // NOI18N
        jLabel1.setText("Appointments");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 128, 39));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "GENDER", "CITY", "COMMUNITY", "VITALS", "Encounter Obj"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 918, 294));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Patient ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 471, -1, 35));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText(" Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 524, 105, 35));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Gender");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 588, 105, 35));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 204));
        jLabel18.setText("City");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 652, 105, 35));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Community");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 471, 118, 35));
        add(patientCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 472, 193, 35));

        patientCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientCityActionPerformed(evt);
            }
        });
        add(patientCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 653, 192, 35));
        add(patientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 589, 193, 35));
        add(patientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 535, 193, 35));
        add(patientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 471, 193, 35));

        patientPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPass1ActionPerformed(evt);
            }
        });
        add(patientPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 192, 35));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 204));
        jLabel20.setText("Vital Signs");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 105, 35));

        search.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(0, 102, 204));
        search.setText("UPDATE");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 625, 147, 49));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/pavan/Downloads/1111.jpg")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 840));
    }// </editor-fold>//GEN-END:initComponents

//            Hospital c = (Hospital)jTable2.getValueAt(jTable2.getSelectedRow(), 4);
//            Doctor d = (Doctor)jTable1.getValueAt(jTable1.getSelectedRow(), 2);
//            Encounter e = new Encounter(d,this.patient);
//            SystemAdmin.encounterList.add(e);
//           
//            JOptionPane.showMessageDialog(null, "Appoointment Booked");
//        }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()>-1 ){
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        Encounter p = (Encounter)model.getValueAt(jTable1.getSelectedRow(), 6);
        patientID.setText(String.valueOf(p.patient.patientID));
        
        patientName.setText(p.patient.name);
        patientGender.setText(p.patient.gender);
        
        patientCity.setText(p.patient.city);
        patientCommunity.setText(p.patient.community);
        } 
    }//GEN-LAST:event_jTable1MouseClicked

    private void patientCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientCityActionPerformed

    private void patientPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPass1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
      
        String vitals = patientPass1.getText();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Encounter p = (Encounter)model.getValueAt(jTable1.getSelectedRow(), 6);
        p.vitalSigns=vitals;
        fillTable();
        SystemAdmin.doctorList.add(doctor);
        JOptionPane.showMessageDialog(null, "Vitals Added");
    }//GEN-LAST:event_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField patientCity;
    private javax.swing.JTextField patientCommunity;
    private javax.swing.JTextField patientGender;
    private javax.swing.JTextField patientID;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField patientPass1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
private void fillTable() {
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       model.setRowCount(0);
       for(Encounter  p : SystemAdmin.encounterList ){
           if(p.doctor==this.doctor){
           Object[] row = new Object[7];
           row[0]= p.patient.patientID;
           row[1]= p.patient.name;
           
           row[2]= p.patient.gender;
           row[3]= p.patient.city;
           
           
           row[4]= p.patient.community;
           row[5]=p.vitalSigns;           
           row[6]= p;
           
           
           model.addRow(row);
       }}}
}
