/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HealthCareUI;

import HealthCare.City;
import HealthCare.Community;
import HealthCare.Hospital;
import HealthCare.Patient;
import HealthCare.SystemAdmin;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pavan
 */
public class SystemAdminAddHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminDoctorJPanel
     */
    public SystemAdminAddHospitalJPanel() {
        initComponents();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        hospName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 188, -1, 35));

        hospName.setBackground(new java.awt.Color(204, 255, 255));
        add(hospName, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 96, 193, 32));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Community");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 250, 140, 35));

        search.setBackground(new java.awt.Color(204, 255, 255));
        search.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(0, 102, 204));
        search.setText("ADD HOSPITAL");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 631, -1, 49));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Username");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 470, 105, 35));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 538, 105, 35));

        user.setBackground(new java.awt.Color(204, 255, 255));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 472, 193, 32));

        pass.setBackground(new java.awt.Color(204, 255, 255));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 540, 192, 32));

        jPanel1.setBackground(new java.awt.Color(93, 154, 244));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADD HOSPITAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(713, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, 1050, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hospital Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 94, 140, 35));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Community Name", "Comm Obj"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 158, 328, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/pavan/Downloads/6.jpg")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 840));
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       if(hospName.getText().trim().equalsIgnoreCase("") ||user.getText().trim().equalsIgnoreCase("")||
                pass.getText().trim().equalsIgnoreCase("")){
                        JOptionPane.showMessageDialog(this, "Empty TextFields");
        }
        if(!Pattern.compile("[a-zA-Z ]+").matcher(hospName.getText()).matches()){
            JOptionPane.showMessageDialog(this, "Please enter valid name");
            return;
//            ([a-z].[0-9])|([0-9].[a-z])
//           
        }
       if(!Pattern.compile("^[a-zA-Z0-9._-]{3,}$").matcher(user.getText()).matches()){
            JOptionPane.showMessageDialog(this, "6");
            return;
        }if(!Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$").matcher(pass.getText()).matches()){
            JOptionPane.showMessageDialog(this, "    Password must contain at least one digit [0-9].\n" +
"    Password must contain at least one lowercase Latin character [a-z].\n" +
"    Password must contain at least one uppercase Latin character [A-Z].\n" +
"    Password must contain at least one special character like ! @ # & ( ).\n" +
"    Password must contain a length of at least 8 characters and a maximum of 20 characters.");
            return;
        }
        if(jTable1.getSelectedRow()>-1){
            String name = hospName.getText();
            for(Hospital p:SystemAdmin.hospitalList){
            if(user.getText().equals(p.getUsername())){
                JOptionPane.showMessageDialog(null, "Username Exist Please Change.");  
                return;
            }
            }
            //         String name = name.getText();
             Hospital hospital = new Hospital(hospName.getText(),user.getText(),pass.getText(),(Community)jTable1.getValueAt(jTable1.getSelectedRow(), 1));
             SystemAdmin.hospitalList.add(hospital);
             JOptionPane.showMessageDialog(null, "Added Hospital.");
        }else{
            JOptionPane.showMessageDialog(null, "Select Community");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hospName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pass;
    private javax.swing.JButton search;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

private void fillTable() {
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       model.setRowCount(0);
       for(Community  p : SystemAdmin.communityList ){
           
           Object[] row = new Object[2];
           row[0]= p.getCommunityName();
           row[1]= p;
           
           
           
           model.addRow(row);
       }}}
