/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Product;
import model.ViewEmployee;

/**
 *
 * @author pavan
 */
public class SearchPanel extends javax.swing.JPanel {
 ViewEmployee view;
 final TableRowSorter<TableModel> sorter;
 DefaultTableModel model;
    
    /**
     * Creates new form SearchPanel
     */
     public SearchPanel(ViewEmployee view) {
        initComponents();
        this.view = view;
        populateTable();
        sorter = new TableRowSorter<TableModel>(model);
        tblView.setRowSorter(sorter);
    }
     
     private void populateTable() {
       model = (DefaultTableModel)tblView.getModel();
       model.setRowCount(0);
       for(Product  p : view.getHistory ()){
           
           Object[] row = new Object[10];
           row[0]= p;
           row[1]= p.getId();
           row[2]= p.getAge();
           row[3]= p.getGender();
           row[4]= p.getStartDate();
           row[5]= p.getLevel();
           row[6]= p.getTeamInfo();
           row[7]= p.getPosition();
           row[8]= p.getMobileNo();
           row[9]= p.getEmail();  
           
           model.addRow(row);
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchBox = new javax.swing.JTextField();
        searchEmp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        searchListBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 203, 203));

        txtSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchBoxActionPerformed(evt);
            }
        });
        txtSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBoxKeyReleased(evt);
            }
        });

        searchEmp.setText("Search");
        searchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpActionPerformed(evt);
            }
        });

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Emp_id", "Age", "Gender", "Start_Date", "Level", "Team_Info", "Position_Title", "Mob_No", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblView);

        searchListBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "ID", "Age", "Gender", "Level", "Position Title", "Email", "Mobile" }));
        searchListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchListBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Search Employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addGap(0, 393, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(txtSearchBox)
                        .addGap(28, 28, 28)
                        .addComponent(searchEmp)))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchListBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEmp))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchBoxActionPerformed

    private void searchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpActionPerformed
        // TODO add your handling code here:
        String column = searchListBox.getSelectedItem().toString();
        String textBoxString = txtSearchBox.getText();
        sorter.setRowFilter(RowFilter.regexFilter(textBoxString));
        
    }//GEN-LAST:event_searchEmpActionPerformed

    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        // TODO add your handling code here:
        //        DefaultTableModel model = (DefaultTableModel)tblView.getModel();
        //        txtName.setText(model.getValueAt(tblView.getSelectedRow(), 0).toString());
        //        txtEmpId.setText(model.getValueAt(tblView.getSelectedRow(), 1).toString());
        //        txtAge.setText(model.getValueAt(tblView.getSelectedRow(), 2).toString());
        //        txtStart.setText(model.getValueAt(tblView.getSelectedRow(), 4).toString());
        //        txtTeam.setText(model.getValueAt(tblView.getSelectedRow(), 6).toString());
        //        txtMobile.setText(model.getValueAt(tblView.getSelectedRow(), 7).toString());
        //        txtEmail.setText(model.getValueAt(tblView.getSelectedRow(), 8).toString());
        //        txtPosition.setText(model.getValueAt(tblView.getSelectedRow(), 9).toString());
    }//GEN-LAST:event_tblViewMouseClicked

    private void searchListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchListBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchListBoxActionPerformed

    private void txtSearchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxKeyReleased
        // TODO add your handling code here:
        String textBoxString = txtSearchBox.getText();
        sorter.setRowFilter(RowFilter.regexFilter(textBoxString));
    }//GEN-LAST:event_txtSearchBoxKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchEmp;
    private javax.swing.JComboBox<String> searchListBox;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtSearchBox;
    // End of variables declaration//GEN-END:variables
}
